### ISSUE TITLE
Why the module implements some logic when installing awscli-bundle.zip

### ISSUE THREAD

**Issue by danifr** [voxpupuli/puppet-archive#146]
Shouldn't this installation be completely configurable via the  `$aws_cli_install` param?
 `$aws_cli_install` should be false by default and if the user wants to install it they just need to set it to true.

This change would let us get rid of this logic https://github.com/voxpupuli/puppet-archive/blob/master/manifests/params.pp#L27

**Comment by nanliu** [comment]
This was intended to simplify the logic in a mixed environment, where the AWS CLI is automatically installed for systems running in AWS. Simply setting it as false would be easier logically, but I was trying to implement a convenient default.

Regarding #141, Dan mentioned openstack use the same metadata service so it will populate ec2_* facts (see https://projects.puppetlabs.com/issues/11640). I didn't anticipate this and since I don't have access to openstack environment, I haven't found the difference between them (in facter). @nibalizer, would you know off the top of your head?

If we can't sort this out soon, I agree we should just change the default to false and remove the logic since it's not working as intended.
