### ISSUE TITLE
Should install dependent packages

### ISSUE THREAD

**Issue by jaxxstorm** [voxpupuli/puppet-archive#154]
I've had rare occasions where I've downloaded a zip for example and the `unzip` package wasn't available.

Are there any thoughts on whether this module should manage the package dependencies it needs to do its job? I personally think it should.

**Comment by nanliu** [comment]
This is left to the consumer of the module: https://github.com/voxpupuli/puppet-archive#setup. profile::archive might be another way to go. I'm not sure I would include such a common package since it might trigger duplicate resource definition so IMO it's better for the user to specify. I'm open to other feedback.

**Comment by jaxxstorm** [comment]
Could we not use `ensure_packages` to avoid the duplicate resource definition? If not, happy to close this

**Comment by nanliu** [comment]
ensure_packages only works if all modules mutually agrees to implement it, otherwise it will not work properly depending on compile order. We could add some additional parameter in the archive class to toggle the install, but which packages should we install by default on each platform?  If Puppet releases an official API for searching through the catalog, it might be worth revisiting since we can search all archive resource and it's file extensions. Until then, I think it's best to let the end user configure a default that's suitable for your environment per setup documentation.

**Comment by jyaworski** [comment]
What about adding a manage_packages param?

**Comment by nanliu** [comment]
I don't feel strongly either way, I guess whoever decide to implement this, just use sensible default packages for each OS and set manage_package to false for backwards compatibility.

**Comment by nibalizer** [comment]
I don't think the archive module should be managing these packages. If someone wants to add a manage_packages parameter ( I would hope it would take an array of packages to install) then that PR would be accepted.
