### ISSUE TITLE
Module Criteria for download / extract on next Puppet Run

### ISSUE THREAD

**Issue by LewR1344** [voxpupuli/puppet-archive#276]
What determines whether the module will perform a new download / extract on the next Puppet run?  We are using the module to download and extract a zip archive in a Linux environment, and we are finding that the module does not seem to detect changes in the content of the zip archive.  The only way we can get the module to re-run is to delete the downloaded zip file after every extract, but that causes the module to download and extract the zip file on every Puppet run.  Our desired behavior is that a new download and extract would occur only when the source zip file changes.

**Comment by nanliu** [comment]
This module uses file checksum to determine if an archive should be downloaded. Because archive files can be very large, it does not download it on every puppet run to compare with the file on disk. There's a few ways to provide checksum metadata besides hardcoded `checksum` value in the puppet manifest such as `checksum_url`. Define types such as artifactory, nexus, and gocd uses the server generated checksum to determine if there's a newer file which should trigger an update.
