### ISSUE TITLE
Add support for S3?

### ISSUE THREAD

**Issue by lindsay-apitalent** [voxpupuli/puppet-archive#48]
Any chance to add support for S3, like for staging module?

**Comment by nanliu** [comment]
Possibly, depends on how much aws-s3 or s3 gem brings in terms of dependency.

**Comment by mpeter** [comment]
Agreed. I'd like to use this module, but it won't be possible until S3 support is added.

**Comment by jcajkovic** [comment]
s3 support is must have for me, any news on this one ?

**Comment by igalic** [comment]
i'm confused about what s3 does different when downloading things from it…

**Comment by jcajkovic** [comment]
Well S3 does not support basic http auth so you need to have aws_cli or ruby aws_sdk in this case to support auth via IAM. Aws_sdk finds credentials on multiple places, in ~/.aws/credentials, as the environment variables or if it is instance running in AWS you can use Instance Profile (I need to support all of them because of multiple environments). Of course there is also possibility of download file via http/https however objects on S3 are available to everybody so it lacks then security at all. In ruby it is very easy to download object from S3, this is my test code:

require 'aws-sdk'

s3 = Aws::S3::Client.new(
  region: 'eu-west-1',
)

resp = s3.get_object({ bucket:'bucket_name', key:'object_key' }, target: 'target_path')

however I'm struggling with the puppet archive type how he decide which provider to use if curl or wget, if I have answer for that maybe I'm able to implement this myself. I have a there that this part of code in curl.rb defaultfor :feature => :posix is telling to use this as default, than I do not understand why wget option is there and how to enable it.

**Comment by nanliu** [comment]
Custom providers are specified via the provider metaparameter:
```puppet
archive { 'example':
  provider => wget,
}
```
So by specifying s3 this will override the default provider:
```puppet
archive { 'example':
  provider => s3,
}
```

**Comment by nanliu** [comment]
aws-sdk gem had a lot of dependency, so I implemented an optional provider based on aws-cli. Probably needs a few more parameters such as ability to select profile. An alternative provider can be implemented by inheriting the base ruby provider and overriding the s3_download method. Please provider testing and feedback on this new feature.

**Comment by igalic** [comment]
:purple_heart: @nanliu you are my hero :purple_heart:

**Comment by Cinderhaze** [comment]
This is great, I just came here to look for this feature!

**Comment by nanliu** [comment]
I don't see a reason to support ETag in archive because AWS CLI performs it already with retry:
http://docs.aws.amazon.com/cli/latest/topic/s3-faq.html#q-does-the-aws-cli-validate-checksums

Please provide testing and feedback. 0.5.0 is a major change, and I'll tackle any bugs people discover asap.

**Comment by Cinderhaze** [comment]
The ETag support is for the cases mentioned in the link you posted..

> 
> There are several conditions where the CLI is not able to verify checksums on downloads:
> 
> If the object was uploaded via multipart uploads
> If the object was uploaded using server side encryption with KMS
> If the object was uploaded using a customer provided encryption key
> If the object is downloaded using range GetObject requests

We have multi-part uploads that create the etag which does not equal the MD5.

I'm still new to implementing types an providers... If you wanted to override the s3_download method, what would the provider look like (minus the implementation). Something like this? (slightly modified from your [gist](https://gist.github.com/nanliu/5eb83f87d53d967885f4/revisions))
```
Puppet::Type.type(:archive).provide(:aws, :parent => :ruby) do
  commands :aws => 'aws'

  def s3_download(filepath)
    # implementation here using the s3api to pull down the etag information from the header along with the file content
    @aws_params = [
      's3',
      'cp',
      resource[:source],
      filepath,
    ]

    aws(@aws_params)
  end
end
```

Would we have to directly provide the provider => 'aws' to the archive resource in our corresponding puppet code to force that to be used?

**Comment by nanliu** [comment]
@Cinderhaze, if this is feature you need please open a new issue. Regarding your questions:

1. Yes, your example would be enabled via provider => 'aws'. 
2. However if you want the file to update when etag changes you probably want to implement the def checksum method and make s3:/// sources default to some checksum type (md5?). This way if puppet detects a checksum difference it will call the s3_download method. If you simply implemented the s3_download method, puppet won't trigger the file download on mismatch etags.
3. filebucket is only available to the file resource. We can add a backup parameter and do a copy of the existing file (I would not use puppet filebucket even if we can call the terminus for these type of large files).
